const Icons = {

    bookmark: require('../assets/bookmark.png'),
    clock: require('../assets/clock.png'),
    bookmark_saved: require('../assets/bookmark_saved.png'),
    close: require('../assets/close.png'),
    course: require('../assets/course.png'),
    reset: require('../assets/reset.jpg'),
    nutrition: require('../assets/nutrition.jpg'),
    food: require('../assets/food.png'),
    garlic: require('../assets/garlic.jpg'),
    righticon: require('../assets/right_arrow.png'),
    gallery: require('../assets/gallery.png'),
    header: require('../assets/header.png'),
    info: require('../assets/info.png'),
    home: require('../assets/home.png'),
    progress: require('../assets/progress.png'),
    inbox: require('../assets/inbox.png'),
    settings: require('../assets/settings.png'),
    progressbar: require('../assets/progressbar.png'),
    dropdown_line: require('../assets/dropdown_line.png'),
    user: require('../assets/user.png'),
    dropup: require('../assets/dropup.png'),
    dropdown: require('../assets/dropdown.png'),
    menu: require('../assets/menu.png'),
    user_avatar: require('../assets/user_avatar.png'),
    profile: require('../assets/profile.png'),
    padlock: require('../assets/padlock.png'),
    communication: require('../assets/communication.png'),
    translate: require('../assets/translate.png'),
    logout: require('../assets/logout.png'),
    right_arrow: require('../assets/right_arrow.png'),
    logo: require('../assets/logo.png'),
    hidden: require('../assets/hidden.png'),
    eye: require('../assets/eye.png'),
    camera: require('../assets/camera.png'),
    left_arrow: require('../assets/left_arrow.png'),
    help: require('../assets/help.png'),


}
export default Icons;